### ISSUE TITLE
App not mounting

### ISSUE THREAD

**Issue by maritaria** [lanlords/discord#5]
I noticed that on https://discord.steamcmd.net/ the vue app doesnt render properly, same occurs for this project which is upstream from the steamcmd one.

Console shows `Uncaught TypeError: Vue is not a constructor`.

I haven't looked into it much but I suspect that the release of Vue 3 may have something to do with it, the breaking changes include how to bootstrap the Vue framework.
Easiest fix is to version pin the library on the cdn based fetch to the most recent v2 version, suffix the cdn url with `@2` seems to work.

**Comment by jonakoudijs** [comment]
Thank you very much for creating the issue, I had not yet noticed this problem. It seems that you are right about the version release. I pinned the most recent v2.x.x version and it seems to be working again.

For now I will not rewrite the code to make it work on version 3 seeing I would like to make this into a Jekyll theme or template at some point. Thanks again for pointing this out :)
